### ISSUE TITLE
plugin.js should use config vars

### ISSUE THREAD

**Issue by outflux3** [BitPoet/ProcessCKInlineComplete#1]
In the plugin.js, the templates appear to be hard coded (?)

shouldn't it be like this around line 266:

var resTpl = config.resultTpl;
var cols = config.returnColumns;

**Comment by BitPoet** [comment]
Definitely. I am going to take a look if I missed other spots as well.

**Comment by BitPoet** [comment]
Fixed in f2e09f463c1b5fa172b2e07dfe64d734ff29b5cd, version bumped to 0.1.8. Please test and close the issue if everything works.

**Comment by outflux3** [comment]
thanks, the fix works!
