### ISSUE TITLE
Image Uploading Problem

### ISSUE THREAD

**Issue by outflux3** [BitPoet/ProcessCKInlineComplete#2]
It appears that the module is interfering with image uploading; What happens is that the module returns the addPlugins() method, ck editor script stuff, even when the request is for the file upload.

adding this as the first line of the addPlugins() method fixes the upload for me:

if($this->input->get('InputfieldFileAjax')) return;

**Comment by BitPoet** [comment]
Thanks for reporting this and the fix. I'm going to tackle this as soon as I find the time, might be a week though since I just returned from a long trip.
