### ISSUE TITLE
Positioning on long fields

### ISSUE THREAD

**Issue by outflux3** [BitPoet/ProcessCKInlineComplete#3]
Hi - 
Been using the module a lot, and it's really awesome. 

One a project that i'm doing now, some of the RTE fields are super long, and the offsets don't work. The popup/select appears way down the page, as the top offset is being calculated based on the height of the iframe which is extremely long with all of that content.

I took a look at the JS and played around a bit, but not sure how to resolve the positioning issue, I couldn't figure it out.  I will try and look at some other CK plugins to see maybe how any other plugins address this and see if i can come up with a fix; In the meantime I did want to check to see if you had made any progress on this positioning problem.

**Comment by BitPoet** [comment]
We have a fix in dev tree thanks to @Toutouwai, merged 9274d7884db7c9bbc44998160efab4dd212fc9ea
